#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${ROOT_DIR}"

PASS_SHARED_ENTRY="${PASS_SHARED_ENTRY:-infra/ghcr/shared}"
PASS_APP_ENTRY="${PASS_APP_ENTRY:-apps/devx-tts/prod}"
OUT_FILE="${ROOT_DIR}/.env.local"

if ! command -v pass >/dev/null 2>&1; then
  echo "ERROR: 'pass' CLI not found in PATH." >&2
  exit 1
fi

TMP_FILE="$(mktemp)"
cleanup() {
  rm -f "${TMP_FILE}"
}
trap cleanup EXIT

for entry in "${PASS_SHARED_ENTRY}" "${PASS_APP_ENTRY}"; do
  if ! pass show "${entry}" >/dev/null 2>&1; then
    echo "ERROR: pass entry not found: ${entry}" >&2
    exit 1
  fi
done

{
  echo "# Generated by scripts/env-sync.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "# source: pass:${PASS_SHARED_ENTRY}"
  pass show "${PASS_SHARED_ENTRY}"
  echo
  echo "# source: pass:${PASS_APP_ENTRY}"
  pass show "${PASS_APP_ENTRY}"
} | awk '
  BEGIN { FS="=" }
  /^[[:space:]]*#/ { next }
  /^[[:space:]]*$/ { next }
  /^[A-Za-z_][A-Za-z0-9_]*=/ { print; next }
  { next }
' > "${TMP_FILE}"

resolve_entry_key() {
  local target_key="$1"
  local entry_key="${target_key}_ENTRY"
  if rg -q "^${target_key}=" "${TMP_FILE}"; then
    return 0
  fi
  if ! rg -q "^${entry_key}=" "${TMP_FILE}"; then
    return 0
  fi

  local entry_path
  entry_path="$(rg "^${entry_key}=" "${TMP_FILE}" -N -m 1 | cut -d= -f2- | tr -d '\r' | xargs)"
  if [[ -z "${entry_path}" ]]; then
    return 0
  fi

  local resolved
  resolved="$(pass show "${entry_path}" | head -n 1 | tr -d '\r')"
  if [[ -z "${resolved}" ]]; then
    echo "ERROR: pass entry '${entry_path}' for ${entry_key} is empty." >&2
    exit 1
  fi

  echo "${target_key}=${resolved}" >> "${TMP_FILE}"
}

while IFS= read -r entry_key; do
  [[ -z "${entry_key}" ]] && continue
  resolve_entry_key "${entry_key%_ENTRY}"
done < <(awk -F= '/^[A-Za-z_][A-Za-z0-9_]*_ENTRY=/{ print $1 }' "${TMP_FILE}" | sort -u)

required_keys=(
  GHCR_USERNAME
  GHCR_TOKEN
  CONTABO_VM_IP
  TTS_DOMAIN
  DEVX_API_KEY
)

for key in "${required_keys[@]}"; do
  if ! rg -q "^${key}=" "${TMP_FILE}"; then
    echo "ERROR: missing required key '${key}' in pass entries." >&2
    exit 1
  fi

  value="$(rg "^${key}=" "${TMP_FILE}" -N -m 1 | cut -d= -f2-)"
  if [[ -z "${value}" ]]; then
    echo "ERROR: required key '${key}' is empty in pass entries." >&2
    exit 1
  fi
done

umask 077
cp "${TMP_FILE}" "${OUT_FILE}"

echo "Wrote ${OUT_FILE}"
echo "Using pass entries:"
echo "  - ${PASS_SHARED_ENTRY}"
echo "  - ${PASS_APP_ENTRY}"